project:
  type: website
  output-dir: docs

website:
  title: "Adam Stein"
  navbar:
    left:
      - text: Resume
        href: resume.qmd
      - text: Projects
        href: projects.qmd

format:
  html:
    theme: cosmo
    csl:  ./assets/nature.csl
    toc: true
    css: styles.css



