project:
  type: website
  output-dir: docs

website:
  title: "Adam Stein"
  back-to-top-navigation: true
  navbar:
    left:
      - text: Resume
        href: resume.qmd
      - text: GU Projects
        href: projects.qmd
      - text: Personal Projects
        href: personal_projects.qmd

format:
  html:
    theme: cosmo
    link-external-newwindow: true
    csl:  ./assets/nature.csl
    toc: true
    css: styles.css



